### ISSUE TITLE
Merge into Baritone

### ISSUE THREAD

**Issue by UltraBlackLinux** [kurrycat2004/MPKMod_2#3]
Hey there,

I was wondering if you could propose a merge into baritone. Baritone is already kinda made for exactly these kind of tasks, and it's parkour system needs a big overhaul anyways (It doesn't even dare 4 block jumps) - This might be a bit overkill, but would mean more maintainers and a good application

I would love to see such a change!

Thanks!

**Comment by kurrycat2004** [comment]
wont merge, for more details look at discussion on discord
https://discord.com/channels/819737524372504587/819742188132761642/1039991619639840789
