### ISSUE TITLE
Landing blocks not rendered properly in 1.20.6

### ISSUE THREAD

**Issue by Zpiboo** [kurrycat2004/MPKMod_2#34]
The player's yaw and pitch seem not to be taken in consideration in 1.20.6 when rendering the landing blocks: if I stand still and just move my mouse, they stay at the same position on the window (where it would be when facing 0 0, or 180 0 depending on my position).
![2024-06-12_15 43 04](https://github.com/kurrycat2004/MPKMod_2/assets/93818768/97f21930-713a-4a0a-b61b-77a71f2514ce)

**Comment by kurrycat2004** [comment]
fixed with [8138092](https://github.com/kurrycat2004/MPKMod_2/commit/8138092)
